export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// FILE: app/(user)/login/layout.js
export default function LoginLayout({ children }) {
  return <>{children}</>;
}
